### DISCUSSION TITLE
Java Agent failed to connect to localhost sidekick

### DISCUSSION THREAD

**Discussion by minuth** [runsidekick/sidekick#68] [Q&A] [answered]
I cannot run the Java agent with the self-hosting sidekick, but there is no problem if I connect this self-hosting with the NodeJS project.

- Error

<img width="1377" alt="Screen Shot 2022-12-07 at 5 51 35 PM" src="https://user-images.githubusercontent.com/33181465/206162411-89698473-0f05-4cd3-84dd-08cd3690a3ab.png">

- Docker file
```
FROM maven:3.8.6-eclipse-temurin-17-alpine AS MAVEN_BUILD

COPY pom.xml /build/
COPY src /build/src/

WORKDIR /build/

RUN mvn -Dmaven.test.skip=true package -Ptest

FROM openjdk:17

WORKDIR /app

COPY sidekick-agent-bootstrap-0.0.14.jar /app/

COPY --from=MAVEN_BUILD /build/target/ecommerceportal-0.0.1-SNAPSHOT.jar /app/

ENTRYPOINT ["java", "-javaagent:sidekick-agent-bootstrap-0.0.14.jar", "-jar", "ecommerceportal-0.0.1-SNAPSHOT.jar"]
```

- Docker compose
```
version: '3.8'
services:
  ecommerceportal-v2:
    build: .
    container_name: 'ecommerceportal-v2-container'
    environment:
      - SIDEKICK_AGENT_BROKER_HOST=ws://127.0.0.1
      - SIDEKICK_AGENT_BROKER_PORT=7777
      - SIDEKICK_APIKEY=my-token
    ports:
      - 8088:8088
```
